baseurl = "http://www.oliverwilkie.com/"
languageCode = "en-us"
title = "Oliver Wilkie"
theme = "hyde"
copyright = "Oliver Wilkie"

[Author]
      name = "Oliver Wilkie"

[Permalinks]
      blog = "/:year/:month/:filename/"

[taxonomies]
      category = "categories"

[params]
      description = "coding and other projects by Oliver Wilkie"
      twitter = "https://twitter.com/oliwilks"
