baseurl = "https://oliverwilkie.com/"
languageCode = "en-us"
title = "Oliver Wilkie"
theme = "hyde"
copyright = "Oliver Wilkie"

[Author]
      name = "Oliver Wilkie"

[Permalinks]
      posts = "/:year/:month/:filename/"

[taxonomies]
      category = "categories"

[params.social]
  twitter = "oliwilks"
  github = "oliw"
  linkedin = "owilkie"

[params]
      description = "Software Engineer"
      twitter = "https://twitter.com/oliwilks"
      themeColor = "theme-base-0b"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = -110
  [[menu.main]]
    identifier = "reviews"
    name = "Reviews"
    url = "/reviews"
    weight = -110