baseurl: "https://oliverwilkie.com/"
languageCode: en-us
title: Oliver Wilkie
theme: hyde-hyde
copyright: Oliver Wilkie
enableGitInfo: true
Author:
  name: Oliver Wilkie
Permalinks:
  posts: "/:year/:month/:filename/"
taxonomies:
  category: categories
frontmatter:
  date:
    - date
    - :git
params:
  social:
    twitter: oliwilks
    github: oliw
    linkedin: owilkie
  description: Software Engineer
  twitter: "https://twitter.com/oliwilks"
  themeColor: theme-base-custom
  highlightjs: true
  highlightjsstyle: rainbow
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: -112
    - identifier: portfolio
      name: Projects
      weight: -110
      url: /portfolio
    - identifier: lists
      name: Lists
      weight: -109
      url: /lists
